### ISSUE TITLE
Cannot pair device - Leila 1.7.0

### ISSUE THREAD

**Issue by rhecko** [palinek/pvr.sledovanitv.cz#51] opened 2020-03-28 21:39 UTC
Hello

I updated to 1.7.0 and I'm unable to see the channels. I get in kodi.log:

2020-03-28 22:37:14.565 T:2512390976   ERROR: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Error indicated in response. status: 0, error: pairing limit reached
2020-03-28 22:37:14.565 T:2512390976   ERROR: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Error in pairing response.
2020-03-28 22:37:14.565 T:2512390976   ERROR: AddOnLog: PVR Client for sledovanitv.cz (unofficial): Cannot pair device

##### System Information

* pvr.sledovani.tv Version:  1.7.0
* Kodi Version: 18.5
* OS Version: Ubuntu 16.04.6 LTS

regards

Robert

**Comment by palinek** [comment] 2020-03-29 09:46
Duplicate of #47

**Closed as completed by palinek** 2020-03-29 09:46 UTC
Labels: duplicate, question
