### ISSUE TITLE
Some XXX stations cannot be switched

### ISSUE THREAD

**Issue by otava5** [palinek/pvr.sledovanitv.cz#81] opened 2021-12-13 20:41 UTC
Some XXX stations cannot be switched, eg to Leo HD. Switching to live but works via "channel program - play program" ...

Can this be fixed?

Could it be added to the settings, PIN settings, so that it does not have to be entered when switching to the program?

Thnx
##### System Information

* pvr.sledovani.tv Version: 20.0.0
* Kodi Version: 19.3
* OS Version: Android / Mi Box S

**Comment by palinek** [comment] 2021-12-14 06:44
Please, be more verbose about the issue you're facing, attach logs etc. With this vague description we can't do much as I can't reproduce such behavior here.

**Comment by otava5** [comment] 2021-12-14 09:04
It does not switch when the channel is started, it only starts when I expand the "channel program" menu and select "play program".
I can send the video but I prefer to link to email ....


##### Log:
[kodi.log](https://github.com/palinek/pvr.sledovanitv.cz/files/7710105/kodi.log)



##### System Information

* pvr.sledovani.tv Version: 4.5.0
* Kodi Version: 19.3
* OS Version: COREELEC

**Comment by palinek** [comment] 2024-01-10 12:39
Followed up and fixed in #107

**Closed as completed by palinek** 2024-01-10 12:39 UTC
Labels: bug
